name: 🧹 Awesome Lint

on:
  push:
    paths:
      - 'README.md'
      - 'data/**'
    branches:
      - main
  pull_request:
    paths:
      - 'README.md'
      - 'data/**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v7

      - name: 🟢 Set up Node
        uses: actions/setup-node@v7
        with:
          node-version: '22'

      - name: 🔍 Run awesome-lint
        run: npx awesome-lint
